config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments, only: [:create]

  root to: 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :body, :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates_presence_of :title, :body, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      render 'posts/show', id: @post.id
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
Welcome to our blog

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path) %>
    </li>
  <% end %>
  <li>
    <%= link_to 'Posts', posts_path %>
  </li>
</ul>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.hidden_field :user_id, value: current_user.try(:id) %>

  <% if @post.errors.any? %>
    Errors: <%= @post.errors.full_messages.join('; ') %>
  <% end %>

  <br/>Title:
  <%= f.text_field :title %>
  <br/>Body:
  <%= f.text_area :body %>

  <br/>
  <%= f.submit (@post.persisted? ? 'Update post' : 'Create post') %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %></br>
  Body: <%= post.body %></br>
<% end %>

<%= link_to "create new post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to @post.title, post_path(@post) %></br>
Body: <%= @post.body %></br>

<%= link_to 'Back', posts_path %>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Delete', post_path(@post), {method: :delete, asdasd: :asdasd} %>

<h3>Comments</h3>

<% @post.comments.each do |comment| %>
  <p><%= comment.body %></p>
<% end %>

<%= form_for @comment do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.try(:id) %>

  <% if @comment.errors.any? %>
    Errors: <%= @comment.errors.full_messages.join('; ') %>
  <% end %>

  <br/>Body:
  <%= f.text_area :body %>

  <br/>
  <%= f.submit (@comment.persisted? ? 'Update comment' : 'Create comment') %>
<% end %>